export default {
  REQUEST_EMPLOYEES_DATA: "REQUEST_EMPLOYEES_DATA",
  REQUEST_EMPLOYEES_DATA_SUCCESS: "REQUEST_EMPLOYEES_DATA_SUCCESS",
  REQUEST_EMPLOYEES_DATA_FAILED: "REQUEST_EMPLOYEES_DATA_FAILED",

  REQUEST_EMPLOYEE_DATA: "REQUEST_EMPLOYEE_DATA",
  REQUEST_EMPLOYEE_DATA_SUCCESS: "REQUEST_EMPLOYEE_DATA_SUCCESS",
  REQUEST_EMPLOYEE_DATA_FAILED: "REQUEST_EMPLOYEE_DATA_FAILED",

  REQUEST_EMPLOYEE_UPDATE: "REQUEST_EMPLOYEE_UPDATE",
  REQUEST_EMPLOYEE_UPDATE_SUCCESS: "REQUEST_EMPLOYEE_UPDATE_SUCCESS",
  REQUEST_EMPLOYEE_UPDATE_FAILED: "REQUEST_EMPLOYEE_UPDATE_FAILED",

  REQUEST_DELETE_EMPLOYEE: "REQUEST_DELETE_EMPLOYEE",
  REQUEST_DELETE_EMPLOYEE_SUCCESS: "REQUEST_DELETE_EMPLOYEE_SUCCESS",
  REQUEST_DELETE_EMPLOYEE_FAILED: "REQUEST_DELETE_EMPLOYEE_FAILED",

  CREATE_EMPLOYEE_ATTENDANCE: "CREATE_EMPLOYEE_ATTENDANCE",
  CREATE_EMPLOYEE_ATTENDANCE_SUCCESS: "CREATE_EMPLOYEE_ATTENDANCE_SUCCESS",
  CREATE_EMPLOYEE_ATTENDANCE_FAILED: "CREATE_EMPLOYEE_ATTENDANCE_FAILED",

  SEARCH_EMPLOYEES_ATTENDANCES: "SEARCH_EMPLOYEES_ATTENDANCES",
};
