export default {
  REQUEST_EMPLOYEE_DATA: "REQUEST_EMPLOYEE_DATA",
  REQUEST_EMPLOYEE_DATA_SUCCESS: "REQUEST_EMPLOYEE_DATA_SUCCESS",
  REQUEST_EMPLOYEE_DATA_FAILED: "REQUEST_EMPLOYEE_DATA_FAILED",

  REQUEST_EMPLOYEE_UPDATE: "REQUEST_EMPLOYEE_UPDATE",
  REQUEST_EMPLOYEE_UPDATE_SUCCESS: "REQUEST_EMPLOYEE_UPDATE_SUCCESS",
  REQUEST_EMPLOYEE_UPDATE_FAILED: "REQUEST_EMPLOYEE_UPDATE_FAILED",

  SET_EMPLOYEE_ATTENDANCE: "SET_EMPLOYEE_ATTENDANCE",
  SET_EMPLOYEE_ATTENDANCE_SUCCESS: "SET_EMPLOYEE_ATTENDANCE_SUCCESS",
  SET_EMPLOYEE_ATTENDANCE_FAILED: "SET_EMPLOYEE_ATTENDANCE_FAILED",
};
